version: "3.8"
services:
  mongodb:
    image: "mango"
    volumes:
      - data:/data/db
  client:
    build: ./client
    ports:
      - "80:80"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - mongodb

  server:
  build: ./server
  port:
    - "3000:3000"
  volumes:
    - ./server/src:/app/src
  stdin_open: true
  tty: true
  depends_on:
    - backend
volumes:
  data:
  logs: